# openapi.yaml
openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
paths:
  /login:
    post:
      summary: Login with email and password
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
              required:
                - email
                - password
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    format: JWT
                  user:
                    $ref: '#/components/schemas/User'
        '401':
          description: Invalid email or password
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /addressTypes:
    get:
      summary: Get List of entities
      description: Returns a list of all entities in the system
      operationId: getEntities
      security:
        - JWT: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/addressTypes'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
  /users/{userId}:
    get:
      summary: Get a user by ID
      description: Returns a single user by ID
      operationId: getUserById
      parameters:
        - name: userId
          in: path
          required: true
          description: ID of the user to retrieve
          schema:
            type: string
      security:
        - JWT: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found
        '401':
          $ref: '#/components/responses/UnauthorizedError'              
  /users:
    get:
      summary: Get all users
      description: Returns a list of all users in the system
      operationId: getUsers
      security:
        - JWT: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
  /countries:
    get:
      summary: Get List of countries
      description: Returns a list of all countries in the system
      operationId: getCountries
      security:
        - JWT: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/countries'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
  /users/{userId}/posts:
    get:
      summary: Get all posts for a user
      description: Returns a list of all posts for a given user
      operationId: getPostsByUserId
      parameters:
        - name: userId
          in: path
          required: true
          description: ID of the user to retrieve posts for
          schema:
            type: string
      security:
        - JWT: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
  /posts:
    get:
      summary: Get all posts
      description: Returns a list of all posts in the system
      operationId: getPosts
      security:
        - JWT: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
components:
  securitySchemes:
    JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    UnauthorizedError:
      description: The user is not authorized to access this resource.
      headers:
        WWW-Authenticate:
          description: The authentication challenge header.
          schema:
            type: string
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  schemas:
    Error:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
      required:
        - code
        - message
    User:
      description: A simple user model.
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
      required:
        - id
        - name
        - email
    countries:
      description: A simple country model.
      type: object
      properties:
        code:
          type: string
        createdAt:
          type: string
        createdBy:
          type: string
        id:
          type: string
        isActive:
          type: string
        name:
          type: string
        oid:
          type: string
        saqaCode:
          type: string
        sarsCode:
          type: string
      # required:
      #   - id
      #   - name
      #   - email
     
    addressTypes:
      description: Address types.
      type: object
      properties:
        code:
          type: string
        createdAt:
          type: string
        createdBy:
          type: string
        description:
          type: string
        id:
          type: string
        isActive:
          type: string
      # required:
      #   - id
      #   - name
      #   - email
    Post:
      type: object
      properties:
        id:
          type: string
        userId:
          type: string
        title:
          type: string
        body:
          type: string
      required:
        - id
        - userId
        - title
        - body
    